### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by AndreiD** [Zewo/WebSocket#12]
Is there a wiki somewhere where newcomers can  read more about how to get started with this ?
Thanks for creating it

**Comment by tomohisa** [comment]
There is not so much of document but 
https://github.com/tomohisa/SwiftSlackBotter
or 
https://medium.com/@pvzig/building-slack-bots-in-swift-b99e243e444c#.ypdezmp7f
uses this framework, it might help you understand usage.

Both of those are client usage though.
