### ISSUE TITLE
fatal error: Index out of range

### ISSUE THREAD

**Issue by goloveychuk** [Zewo/WebSocket#5]
https://github.com/Zewo/WebSocket/blob/master/Sources/Socket.swift#L395

The index here can be -1

Don't know what this code do, but checking for != -1  solves a runtime error
```swift
let ind = frames.endIndex.predecessor()
if ind != -1 {
    frames[ind] = frame
}
```

Also it was impossible to understand where bug was. 
Stack trace from SPM:
```
fatal error: Index out of range
Current stack trace:
[1]    93505 illegal hardware instruction  .build/debug/Broq
```
Xcode showed random line of code each time.  Looks like it's swift debugger error.

**Comment by paulofaria** [comment]
Can you please send a PR?
